# Generated by Django 4.2.2 on 2023-06-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('profile_picture', models.CharField(max_length=200)),
                ('reas_of_expertise', models.CharField(max_length=200)),
            ],
        ),
    ]
